### ISSUE TITLE
fetch资源的时候报错

### ISSUE THREAD

**Issue by quanxin** [smallmuou/xmlyfetcher#11]
fetch资源的时候报错：
parse error: type 'object' has no elements to extract (arg 2)

请教一下该如何处理呢？谢谢

**Comment by smallmuou** [comment]
请求的参数是多少

**Comment by ilovefood2** [comment]
i have same error msg

./xmlyfetcher -o ./tmp https://www.ximalaya.com/youshengshu/18416059

这个有声书前面是免费章节，后面付费，付费的我买了几集做测试，结果就是只能下来前面免费的
然后就开始不停循环下载前面page1的几集，一直循环。。。。

**Comment by silenceleaf** [comment]
一样的问题，付费资源不能下载

**Comment by quanxin** [comment]
> 请求的参数是多少

我重新试了一下，又可以下载了，不知道是不是我前几天使用姿势不对。。。
不过如ilovefood2和silenceleaf所说，试听的章节可以下载，但是付费的部分好像就不能下载了。这个可能和这个工具本身没有关系吧。譬如 
xmlyfetcher https://www.ximalaya.com/youshengshu/19191872/134866881
BTW，感谢提供这样的下载工具:)

**Comment by quanxin** [comment]
另外， 像https://www.ximalaya.com/youshengshu/19191872/p2/ 这个链接，是整个专辑的第二页，上面的第一条音频虽然也是试听内容，但是也无法下载。。整个专辑的链接能把第一页的下载完，第二页的就不能下载了，会转而重新开始下载第一页已经下载过的内容。

**Comment by smallmuou** [comment]
付费确实没有试过

**Comment by ilovefood2** [comment]
又试了下 付费的部分 哪怕买了 也不能下 且会一直循环overwrite  前面已经下来的audio file
