### ISSUE TITLE
资源无法下载

### ISSUE THREAD

**Issue by rayblade** [smallmuou/xmlyfetcher#15]
此URL资源无法下载
https://www.ximalaya.com/waiyu/4323746/17728518

错误提示信息：
[INFO] Fetch track 1/1 ...
./零起点英语Lesson 10-(There is / are...).mp3: 没有那个文件或目录

环境：
Python 2.7.13
Debian 9

**Comment by smallmuou** [comment]
已修复，由于包含了/ .导致无法创建文件
