### ISSUE TITLE
您好，make编译错误了如何解决

### ISSUE THREAD

**Issue by 17764591637** [smallmuou/xmlyfetcher#3]
make编译不通过

**Comment by smallmuou** [comment]
jshon是第三方json解析工具；编译报什么错误，可以把错误信息贴下

**Comment by 17764591637** [comment]
好的。报错放上来了，我自己试了一下网上的方法，并行不通。我去安装jansson，好像也不行，不知道什么原因。
用的是python3.6

rps@rps:~/jshon-20120914$ make
cc -std=c99 -Wall -pedantic -Wextra -Werror    -c -o jshon.o jshon.c
jshon.c:8:21: fatal error: jansson.h: 没有那个文件或目录
compilation terminated.
<builtin>: recipe for target 'jshon.o' failed
make: *** [jshon.o] Error 1

**Comment by smallmuou** [comment]
拷贝jshon可执行文件到系统bin下

**Comment by smallmuou** [comment]
cp jshon /usr/local/bin/

**Comment by smallmuou** [comment]
拷贝jshon可执行文件到系统bin下   sudo cp jshon /usr/local/bin/

**Comment by 17764591637** [comment]
这次是运行了没有报错，但是也没有反映。
rps@rps:~/jshon-20120914/xmlyfetcher$ xmlyfetcher http://www.ximalaya.com/10553948/album/260744/ 
rps@rps:~/jshon-20120914/xmlyfetcher$ xmlyfetcher http://www.ximalaya.com/10553948/album/260744/

**Comment by smallmuou** [comment]
喜马拉雅的地址已经更新了：https://www.ximalaya.com/ertong/260744/

**Comment by 17764591637** [comment]
可以用了，谢谢！
