### ISSUE TITLE
好像不能自动翻页？

### ISSUE THREAD

**Issue by zhiliang-lin** [smallmuou/xmlyfetcher#4]
好像是只能下载当前页面，作者能否再升级一下，让程序可以自动翻页呢？

**Comment by randyzer** [comment]
我是第一次使用github的初学者，请问这个代码必须运行在linux系统下才能下载音频吗？如何在windows环境下使用？谢谢！

**Comment by smallmuou** [comment]
对，这个是linux的脚本命令，windows目前还不支持
