### ISSUE TITLE
https://www.ximalaya.com/ertong/383939/ 下载失败

### ISSUE THREAD

**Issue by bluerubyone** [smallmuou/xmlyfetcher#6]
xmlyfetcher https://www.ximalaya.com/ertong/383939/

warning: nothing to read
internal error: stack underflow
json read error: line 2 column 0: '[' or '{' expected near end of file
json read error: line 2 column 0: '[' or '{' expected near end of file
/usr/local/bin/xmlyfetcher: line 167: [: %: integer expression expected
/usr/local/bin/xmlyfetcher: line 169: ((: i<=/: syntax error: operand expected (error token is "/")
[[1;32mINFO[0m] Contain 0 track(s), start fetch ...

**Comment by liaochenlanruo** [comment]
我也遇到了该问题

**Comment by ikelca** [comment]
same issue

**Comment by gaofengg** [comment]
我也遇到了相同的问题，求解决。

**Comment by smallmuou** [comment]
已修复
