### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ilovefood2** [smallmuou/xmlyfetcher#7]
warning: nothing to read
internal error: stack underflow
json read error: line 2 column 0: '[' or '{' expected near end of file
json read error: line 2 column 0: '[' or '{' expected near end of file
expr: syntax error
expr: syntax error
/usr/local/bin/xmlyfetcher: line 167: [: -ne: unary operator expected
/usr/local/bin/xmlyfetcher: line 170: ((: i<=: syntax error: operand expected (error token is "<=")
[INFO] Contain 0 track(s), start fetch ...

**Comment by smallmuou** [comment]
已修复
