### ISSUE TITLE
 专辑无法下载

### ISSUE THREAD

**Issue by robinlx** [smallmuou/xmlyfetcher#8]
$ xmlyfetcher  https://www.ximalaya.com/ertong/6233693/
warning: nothing to read
internal error: stack underflow
json read error: line 2 column 0: '[' or '{' expected near end of file
json read error: line 2 column 0: '[' or '{' expected near end of file
/usr/local/bin/xmlyfetcher: line 167: [: %: integer expression expected
/usr/local/bin/xmlyfetcher: line 169: ((: i<=/: syntax error: operand expected (error token is "/")
[INFO] Contain 0 track(s), start fetch ...

修复方法：
sed -n 's/.*AlbumDetailTrackList":\(.*\)};<\/script>.*$/\1/p'

第一次在github上提issue，我怎么直接修改后提交呢

**Comment by gaofengg** [comment]
兄弟，可否给个详细的修改说明，请问你的修复方法里的这行代码是修改原文件的哪一行？

**Comment by robinlx** [comment]
我已经提交了request，你在作者的库里面应该也能看到
[cid:image001.png@01D50B2C.4AB6D3E0]

发件人: GaoFeng <notifications@github.com>
发送时间: 2019年5月15日 14:39
收件人: smallmuou/xmlyfetcher <xmlyfetcher@noreply.github.com>
抄送: robinlx <robin_xuan@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [smallmuou/xmlyfetcher] 专辑无法下载 (#8)


兄弟，可否给个详细的修改说明，请问你的修复方法里的这行代码是修改原文件的哪一行？

**Comment by smallmuou** [comment]
已支持专辑下载
